language:
  ruby

rvm:
  - '2.5.1'
  - '2.7.1'

matrix:
  allow_failures:
    - rvm: '2.0'
  fast_finish:
    true

script:
  - bundle add yard-junk
  - bundle install
  - bundle exec rspec
  - bundle exec rubocop
  - bundle exec yard-junk

install:
  - gem install bundler
  - gem install rainbow -v '2.2.1'
  - bundle install

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libmagickwand-dev imagemagick
